spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start_and_stop
spring.docker.compose.stop.command=stop

storage.endpoint=https://${STORAGE_NAMESPACE}.compat.objectstorage.${STORAGE_REGION}.oraclecloud.com
storage.region=${STORAGE_REGION}
storage.access-key=${STORAGE_ACCESS_KEY}
storage.secret-key=${STORAGE_SECRET_KEY}
storage.bucket-name=${STORAGE_BUCKET}

logging.structured.format.console=ecs
logging.structured.format.file=ecs

logging.file.name=logs/app.log
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.file-name-pattern=logs/app-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB

# -----------------------my configs------------------------
cpf.encription-key=${CPF_ENCRYPTION_KEY}

storage.my-local-storage=./documents/uploads
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=5m
jwt.refresh-token-expiration=1h
