spring.application.name=backend

spring.datasource.url=jdbc:h2:file:./data/syndica

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# -----------------------my configs------------------------
jwt.secret=uma-chave-bem-longa-e-aleatoria-de-pelo-menos-256-bits
jwt.access-token-expiration=5m
jwt.refresh-token-expiration=1h
